acikkaynak/deprem-yardim-frontend

.prettierignore, .prettierrc, components/ResponsiveAppBar.tsx, hooks/useAsync.tsx, hooks/useCopyToClipboard.tsx, hooks/useEventListener.tsx, hooks/useFetch.tsx, hooks/useKeypress.tsx, hooks/useLocalStorage.tsx, hooks/useOnWindowResize.tsx, hooks/useOnWindowScroll.tsx, next.config.js, package.json, pages/_app.tsx, pages/_document.tsx, pages/api/hello.ts, pages/index.tsx, styles/Home.module.css, styles/globals.css, utils/createEmotionCache.ts, utils/theme.ts, yarn.lock
=> feat: add prettier

.npmrc, .nvmrc, package.json
=> feat: add nvm and npm configs

.eslintrc.json
=> feat: add eslintrc

.vscode/settings.json
=> build: implement vscode project settings

.vscode/launch.json, package.json, yarn.lock
=> build: add debugging configuration

components/Map.tsx
Harita koordinatlarini depremden etkilenen bolgeye odaklar.
closes #23
=> feat(#23) Harita merkez koordinatlarini degistirir

README.md
closes #29 
- iletisim bilgileri readme'ye eklendi
=> feat(29): iletisim bilgilerinin eklenmesi

components/UI/Map/LeafletMap.tsx
- harita koordinatlarini depremden etkilenen bolgeye degistirir.
=> feat: harita koordinatlarini degistirir

components/UI/Map/LeafletMap.tsx
KGM WMTS server linki bağlandı
=> Feature 42 KGM Altık Haritası eklendi.

components/UI/Map/LeafletMap.tsx
=> fix: remove market icons

components/UI/Drawer/Drawer.tsx, components/UI/Map/DynamicMap.tsx, pages/index.tsx
=> Resolve #77

components/UI/Drawer/Drawer.tsx, components/UI/Map/LeafletMap.tsx
So that we can change whatever we want from just one point
=> fix: generate google maps url from one point

components/UI/FooterBanner/FooterBanner.module.css, components/UI/FooterBanner/FooterBanner.tsx
Ekranın altında bulunan açıklama yazısı gizlenebilir hale getirildi.
=> Açıklama yazısı gizleme

README.md
Adding Turkish information to README.
=> feat: update readme with turkish

README.md
Update readme techs with links
=> feat: update readme techs with links

components/UI/Map/Map.module.css, components/UI/Map/MapLegend.tsx
=> feat: update legend with popover

styles/Home.module.css
This pr adds pulse animation and flex style for logo.
=> style: add logo style

.gitignore, components/UI/FooterBanner/FooterBanner.module.css, components/UI/Map/Map.module.css, pages/index.tsx, styles/Home.module.css
[Issue 132](https://github.com/acikkaynak/deprem-yardim-frontend/issues/132)
=> fix: map legend border radius, logo and link

components/UI/FooterBanner/FooterBanner.module.css
https://github.com/acikkaynak/deprem-yardim-frontend/issues/139
=> feat: footer set border-rad + align

components/UI/Map/ImpactedCities.tsx, components/UI/Map/LeafletMap.tsx, components/UI/Map/Map.module.css
=> feat: add impacted city button to the right side

components/UI/ClusterPopup/ClusterPopup.tsx
=> fix: close btn clusterpopup

components/UI/Button/HelpButton.tsx, components/UI/FooterBanner/FooterBanner.module.css, pages/index.tsx, styles/Home.module.css
https://github.com/acikkaynak/deprem-yardim-frontend/issues/156
- The banner at the bottom overlapped the "Yardim Istemek Icin Tikla" button. Increased the bottom spacing from 20px to 130px. 
- Created a new component call as `HelpButton`.
- Banner `z-index` reduced to `998` to avoid issues with other screen sizes.
=> fix: [#156] fix the overlapping issue on the CTA button in mobile

pages/index.tsx
=> fix: performance issues when initial and drag

components/UI/Drawer/Drawer.module.css, components/UI/Drawer/Drawer.tsx, mocks/handlers.ts, mocks/types.ts, utils/dataTransformer.ts
Add source data for drawer section
=> Add source data for drawer section

components/UI/FooterBanner/FooterBanner.module.css, components/UI/FooterBanner/FooterBanner.tsx, styles/Home.module.css
[issue 175](https://github.com/acikkaynak/deprem-yardim-frontend/issues/175)
=> fix: footer logo css overlap issue fixed

components/UI/Drawer/Drawer.module.css, components/UI/Drawer/Drawer.tsx
Ships https://github.com/acikkaynak/deprem-yardim-frontend/issues/188
=> feat: get directions button in drawer

components/UI/Map/DynamicMap.tsx, components/UI/Map/LeafletMap.tsx
haritanın ülke koordinatlarına göre sınırlandırılması
=> feat(map): limit zoom & bbox 

components/UI/Map/LeafletMap.tsx
Reverts acikkaynak/deprem-yardim-frontend#198
=> Revert "feat(map): limit zoom & bbox "

components/UI/ClusterPopup/ClusterPopup.module.css, components/UI/ClusterPopup/ClusterPopup.tsx, components/UI/Drawer/Drawer.tsx
Ships https://github.com/acikkaynak/deprem-yardim-frontend/issues/219
=> feat: add get direction button to cluster popup

components/UI/FooterBanner/FooterBanner.tsx
Çoklanan Yardım İsteme (Kırmızı buton) butonu kaldırıldı.
=> fix: removed duplicated footer button

components/UI/Drawer/Drawer.tsx
=> fix: drawer overflow

pages/TechnicalError.tsx, pages/index.tsx
=> fix: error handling

components/UI/Map/LeafletMap.tsx, components/UI/Map/utils.ts, pages/index.tsx, stores/mapStore.tsx
=> feat: add responsive zoom level

components/UI/Map/utils.ts
şu şekilde sayfa ilk yüklendiğinde ülke haritası ortalanmış şekilde geliyor
=> fix map zoom on initial load

components/UI/Map/utils.ts
new coordinates: pazarcik/kahramanmaras
=> fix: change default center to new coordinates

çabucak-ogren.md
Kişilerin hazırlanan uygulamayı kullanması için kısa bir kılavuz belgesi yazdık.
=> Çabucak öğren kılavuzu

pages/index.tsx
Summary
Add open graph meta tags
=> chore: add open graph meta tags

components/UI/Map/LeafletMap.tsx, components/UI/Map/utils.ts
=> fix: default min zoom for mobile

components/UI/Head/Head.tsx, pages/index.tsx
Head kısımları index içinde çok fazla kalabalık yaptığı için kendi componentına taşıma ihtiyacı duydum.
=> refactor: app head is moved to its own component

utils/constants.ts
=> fix: new BASEURL

components/UI/Button/CopyButton.tsx, components/UI/ClusterPopup/ClusterPopup.tsx, components/UI/ClusterPopup/index.ts, components/base/Snackbar/Snackbar.tsx, components/base/Snackbar/index.ts, components/base/Snackbar/useSnackbar.ts, package.json, pages/_app.tsx, pages/index.tsx, yarn.lock
=> ClusterPopup component re-design/responsive & Snackbar component created 

components/UI/Map/utils.ts
=> chore: Update zoom and change default center location

components/UI/Map/LeafletMap.tsx
=> Update initial values of map corners

components/UI/Common/LoadingSpinner.module.css
=> feat: update spinner not to block user

components/UI/Common/LoadingSpinner.module.css, components/UI/Common/LoadingSpinner.tsx
#384 ile gelen eksikligi gidermek icin
=> Slow loading text yeni loader kutusuna sigmiyor

çabucak-ogren.md
1. Bilgilerde anlaşılırlık sağlandı.
2. Bilgisayar ve telefon ile uygulamayı kullanma görüntüsü eklendi.
3. Güncellenen sürüme göre tutuşmayan bilgiler değiştirildi.
4. Kılavuzda ölçü birimleri için kullanılan adlar yerine daha düzenli uyumlu adlar yazıldı.
=> İçerik derlendi toplandı

components/UI/Map/LeafletMap.tsx
=> feat(leaflet):  Leaflet cluster componentlerinin harita uzerindeki okunulabilirligi arttirldi #432

components/UI/FooterBanner/FooterBanner.tsx, pages/index.tsx
- Sayfanin her harekette yenilenmesi yerine manual olarak yenilenmeyi tetikleyen buton eklendi.
=> Feature: Adding a new Button to trigger the API request #407

components/UI/Drawer/Drawer.module.css, components/UI/Drawer/Drawer.tsx, components/UI/FooterBanner/FooterBanner.module.css, components/UI/Map/Map.module.css
- Drawer'a extra padding eklendi.
- Twitframe height düşürüldü, scroll behavior eklendi ve scroll width "thin" olarak değiştirildi.
- Footer Banner'da bulunan metin düzgünce hizalandı, extra padding eklendi ve arkaplan rengi yardım butonu ile uyumlu hale getirildi.
- Map Legend'a 150ms transition eklendi ve de gereksiz border kaldırıldı.
=> fix: Updated Drawer, Footer and Map Legend

components/UI/FooterBanner/FooterBanner.tsx, pages/index.tsx
- Sayfayi yenileyen butonun lokasyonu sitenin ust tarafina tasindi.
=> fix: updating the location of the button for triggering the API

styles/Home.module.css
=> Sağ alttaki logo buton olarak algılandığı için opacity düşürdük. resolves #445

components/UI/ClusterPopup/ClusterPopup.tsx
-Cluster pop heading font-size büyütüldü
-Cluster pop width 455px olarak değiştirildi ve böylelikle paddingler düzeldi
-Butonlar gereğinden fazla büyük olduğu için yükseklikleri 3rem olarak değiştirildi ve de font-size 11.7px olarak ayarlandı
=> fix: changes on cluster pop width, heading size and button heights #444

components/UI/Map/LeafletMap.tsx
This PR updates the map boundary corners so we can navigate to nearby cities like Diyarbakir on the map.
=> fix: boundary corners updated to cover nearby cities #437

components/UI/ClusterPopup/ClusterPopup.tsx, components/UI/Drawer/Drawer.module.css
=> fix: Popup butonları container boyutuna göre boyut almıyor #438

components/UI/Map/LeafletMap.tsx, mocks/types.ts, pages/index.tsx, stores/mapStore.tsx
=>  Zoom in/out ve pan edilince marker datası artık çekilmiyor, sadece harita init olunca ve "BU ALANI TARA" butonuna basılınca çekiliyor. resolves #459

mocks/handlers.ts
Dev ortamında msworker tarafında url'nin güncellenerek mock data ile çalışılması için yapılan geliştirmedir.
=> chore: mock api url changed with constant #450

components/UI/Common/TechnicalError.module.css, components/UI/Common/TechnicalError.tsx
=> feat: added reload to technical error component #464

pages/index.tsx
=> Fixes non-updating URL on button click and map init

pages/index.tsx
İlgili issue: https://github.com/acikkaynak/deprem-yardim-frontend/issues/468
=> fix: search area button appearance fix on maintenance #468

.github/PULL_REQUEST_TEMPLATE.md, components/UI/Map/LeafletMap.tsx
=> feat: Leaflet Hash'in kullanılması #431

components/UI/Button/CopyButton.tsx, components/UI/ClusterPopup/ClusterPopup.tsx, components/UI/Drawer/Drawer.tsx, components/UI/Tag/Tag.types.ts, pages/index.tsx
=> fix: cluster popup ui responsivity fix #454

components/UI/FooterBanner/FooterBanner.tsx
- sag alttaki logonun kaldirildi tekrar kullanilabilmesi icin componenti kaldirmadim
**feat(#499)**
Sağ alttaki logo kaldırıldı. Tekrar kullanılabilmesi olası olduğu için componenti kaldırmadım. Gerekirse kaldırabilirim
devtools üzerinden test ettim bir sıkıntı göremedim
* Donanım:
* Toolchain:
* SDK:
=> feat(499): sag alttaki logonun kaldirilmasi

components/UI/Drawer/Drawer.tsx
1. 'Google Haritalarda Ac' buttonuna tiklandiginda acilan yeni pencerede bos bir harita yerine marker ile harita acildi
2. 'Apple Haritalarda Ac' buttonuna tiklandiginda acilan yeni pencerede bos bir harita yerine marker ile harita acildi
Degisiklik sebebi: Google ile olan yonlendirmelerde marker atildigi takdirde marker atilan yerde Google Street View daha rahat kullanilabilir. Simdiden elinize saglik
=> feat: (map redirections) harita yonlendirmeleri marker implementasyonu (feat: #479)

components/UI/Map/utils.ts
**Closes #510**
Uygulamaya telefondan girin ve default zoom'un değiştiğini görün.
=> fix(#510): change default zoom for mobile

components/UI/ClusterPopup/ClusterPopup.tsx, components/UI/Drawer/Drawer.tsx, components/UI/FooterBanner/FooterBanner.tsx, hooks/useDisableZoom.ts
**(#523)**
Map üzerinde ClusterPop'upları zoomlandığından UI problemine yol açıyor. Zoom out yapılamıyor. PopUp zoom'u kısıtlanırsa problem gidecektir
iOS, Android, Chrome, Firefox, Safari platformlarında testler yapıldı
=> fix(#523): cluster popup zoom fix on clusterpopup component

pages/_document.tsx
**discord kullanıcı adı:**  `@Umut K.#4788`
**closes #534**
Test edilmesine gerek duyulmadı.
=> feat(#534): html lang property to tr

components/UI/ClusterPopup/ClusterPopup.tsx, components/UI/Drawer/Drawer.tsx, components/UI/FooterBanner/FooterBanner.tsx, components/UI/GenericError/GenericError.tsx, components/UI/Map/LeafletMap.tsx, hooks/useDisableZoom.ts, mocks/TypesAreasEndpoint.ts, mocks/handlers.ts, mocks/types.ts, pages/_document.tsx, pages/index.tsx, services/dataFetcher.ts, utils/constants.ts, utils/dataTransformer.ts, utils/urls.ts
**discord kullanıcı adı: @afetharita#0001**
* Donanım:
* Toolchain:
* SDK:
=> RC deployment

pages/index.tsx
BU ALANI TARA buttonunun sag ustteki iconlarin yazilarinin ustunde kalmamasi icin z-index degerini adjust ettim.
**discord kullanıcı adı: @onurbayindir#9293
Her icon in ustune gelerek button un onunde display edildigini birkac farkli boyutta test ettim.
* Donanım:
* Toolchain:
* SDK:
=> fix: changing the z-index of the trigger API button to display the text of Icons

components/UI/FooterBanner/FooterBanner.module.css
-Footer banner height & width değişiklikler yapıldı, fazla yer kaplamaması göze alındı.
-Letter spacing mobile ve masaüstüne uygun şekilde refactor edildi.
**discord kullanıcı adı: Çağrı#3568**
**closes #542**
* Donanım:
* Toolchain:
* SDK:
=> fix: changes on footer banner height & width, letter spacing #542

components/UI/Button/LoadArea.tsx, components/UI/Common/LoadingSpinner.module.css, components/UI/Common/LoadingSpinner.tsx, pages/index.tsx, styles/Home.module.css
**discord kullanıcı adı: eytan**
**closes #472**
Yukleniyor ve alani tara butonlari birlestirildi. 
**Desktop**
**Mobil**
Chrome ve Safari de desktop test ettim. Mobil goruntuleri de emulatorlerde test ettim
=> feat(#472): yukleniyor ile alani tara butonunu birlestir

components/UI/Drawer/Drawer.module.css, components/UI/Drawer/Drawer.tsx, utils/date.ts
Drawer componentinde kaydın/bildirimin oluşturulduğu andan itibaren ne kadar vakit geçtiğini göstermek için bir `timeAgo` fonksiyonu oluşturdum ve component üzerinde kullandım.
**discord kullanıcı adı: sametcodes#0001**
**closes #538**
Masaüstü ve mobilde test ettim.
* Donanım:
* Toolchain:
* SDK:
=> feat (#538): added time ago label in the drawer component

components/UI/Drawer/Drawer.tsx
Sistemde Google Maps tarafina gonderilen gereksiz bir parametre, mobil cihazlarda google maps yuklu ise konumu acip marker atmayi blokluyor. Yapilan parametre silinme islemi bu bug'i ortadan kaldirir
**discord kullanıcı adı: @cemiluzunhasan#5776**
**closes #541 **
Degisiklikler
1. Google Maps deep link' indeki `loc` parametresi kaldirildi
Masaustunde ve mobil app'te manual (loc parametresi olmadan) konum girilerek test edildi.
* Firmware versiyonu: 
* Donanım: iPhone 12 with a Google Maps App
* Toolchain:
* SDK:
=> fix (#541): Google Maps loc parametresinin kaldirilmasi

components/UI/Map/LeafletMap.tsx
**discord kullanıcı adı: @Yuiji#8166**
**closes #484**
Kordinat ve zoom level url'e set edilirken router.push() kullanıldığı için re-render oluyordu ve performans sorunlarına yol açıyordu. router.push window.history.repalceState() ile değiştirildi.
Harita'da zoom ve move yapıldığında takılma gözlenmedi. Map'in re-render olmadığı dev modunda test edildi.
Windows işletim sisteminde Chrome, Firefox tarayıcılarında test edildi.
=> fix(#484): UI'da halt/freeze sorunu

components/UI/Common/LoadingSpinner.module.css, pages/index.tsx, styles/Home.module.css
ALANI TARA buttonunun gorselinde ufak degisiklikler yapildi.
Alt alta iki button vardi birini silindi.
Yukleniyor yazisindaki Loaderdaki timer asagiya kaydirildi
**discord kullanıcı adı: @onurbayindir#9293**
**closes #560**
Sadece goruntu bazli degisiklik oldugu icin fonksiyonu etkileyecek herhangi bir degisiklik yapilmadi.
* Donanım:
* Toolchain:
* SDK:
=> refactor(#560): updating the visual of the button for triggering the API

components/UI/Map/ClusterGroup.tsx, components/UI/Map/LayerControl.tsx, components/UI/Map/LeafletMap.tsx, components/UI/SitesIcon/Icons.tsx
=> Katmanların yönetilebilmesi için Layers ikonu 

components/UI/SitesIcon/Icons.tsx
Sağ üstteki link açıklamalarının anlaşılır hale getirilmesi işi.
issue: https://github.com/acikkaynak/deprem-yardim-frontend/issues/536
**discord kullanıcı adı: @İlker Sarıca#7138**
* Donanım:
* Toolchain:
* SDK:
=> fix(#536): website link description fixes

components/UI/Drawer/Drawer.tsx, mocks/types.ts, pages/index.tsx, stores/mapStore.tsx
**discord kullanıcı adı: buraksaraloglu#3182**
**closes #518 **
Kod standardini iyilestirmek icin tekrarlanmis typelari ortaklastirma PR'i.
=> refactor(#518): reduce duplicate type usage

components/UI/SitesIcon/Icons.tsx
afetbilgi.com sağ üstteki linklere eklenildi. Site iconu olmadigi icin ilgili yazi eklenildi.
discord kullanıcı adı: AHMETenes#9745
issue: #570
- bagimlilik gerekmiyor.
dev ortami kullanildi. genislik yukseklik gibi tasarimsal ozellikler saptanildi.
=> feat(new link): added afetbilgi.com to top links #570

pages/index.tsx
fixes: #578 useSWR mutate fonksiyonu için url stale kalıyor, en hızlı çözüm doğrudan state güncellemek gibi timer sonlandığında.
**discord kullanıcı adı: @olcaydogan#0228**
**closes #578 **
* Donanım:
* Toolchain:
* SDK:
=> fix (#578): Otomatik tarama guncel koordinatlari request de eklemiyor

components/UI/Drawer/Drawer.tsx
**discord kullanıcı adı: @nejatcanunlu | Coniun#5462**
**closes #591**
Afetharita'da markerlara tıklanınca solda açılan drawer'da yarım içeriği, tweet v.s. overflow ediyordu, drawer'ı scrollable hale getirdim.
- [x ] Kendi kodumu inceledim, review ettim.
- [ x] Approved tagine sahip bir issue için PR açılmalıdır. Aksi takdirde PR reddedilecektir.
- [ x] İlgili issue numarası: PR ile ilgili issue numarası, PR başlığının başına, prefix sonrası parantez içinde # ile eklenmelidir. "prefix(#issue_number): PR başlığı" şeklinde bir başlık kullanılabilir.
- [ x] Açıklayıcı ve anlaşılır bir başlık: PR başlığı, değişikliklerin niteliklerini ve amaçlarını açık bir şekilde tanımlamalıdır. Pr başlığı, PR açıldığında görüntülenen ilk şey olmalıdır. Ve …
=> Drawer'a tweet içeriği sığmadığı için detay görünemiyordu, artık tamamen scrollable. fixes #591

components/UI/Map/utils.ts
**discord kullanıcı adı: @eytan**
**closes #583**
Default zoom seviyeleri hem desktop hem de mobile icin 8'e alindi butun afet bolgesini gosterebilmek adina.
**Mobil**
**Desktop**
Chrome ve Safari'de test edildi. Mobile test icin de Chrome emulator kullanildi
=> fix(#583): adjust default zoom levels to fit affected area

hooks/useMapClickHandlers.ts
Drawer içerisinde "Escape" harici tuşlamaların drawerı kapatması engellendi
**discord kullanıcı adı: Hakan Angın#9836**
**closes #598**
* Donanım:
* Toolchain:
* SDK:
=> fix(#598): google maps adresi kopyalarken geolocation info ekranının kapanması

pages/index.tsx, styles/Home.module.css
Otomatik tarama yazısı ortalandı ve issue daki ekran görüntüsündeki gibi stil düzenlemeleri yapıldı.
**discord kullanıcı adı: @Umut İncek#8781
**closes #566 **
* Donanım:
* Toolchain:
* SDK:
=> feat(#566) fix: align center and change style for scanning text

.github/workflows/lighthouse-audit.yaml
Vercel'in urettigi preview linkinde ve guncel `rc` URL'inde ayri ayri Lighthouse testi kosturup elde ettigimiz sonuclar ile bir ozet olustururan ve bunu comment olarak pull request'e ekleyen yeni bir GitHub Action eklendi. Ornek cikti/comment asagidan incelenebilir.
**discord kullanıcı adı: @puskuruk 
**closes #613**
* Donanım:
* Toolchain:
* SDK:
=> feat(#613): Add Lighthouse results for preview URLs to pull requests

components/UI/SitesIcon/Icons.tsx
**discord kullanıcı adı: autoMagic#2912**
**closes #622 **
Sağ üst kısımdaki afet bilgi kısmına mouse ile gidin
=> fix: change mask background to transparent for afetBilgi

components/UI/Drawer/Drawer.tsx, components/UI/Map/ClusterGroup.tsx, components/UI/Map/LeafletMap.tsx, components/base/HeadWithMeta/HeadWithMeta.tsx
cluster renderından kaynaklanan freeze için kirli bir çözüm
=> fix: cluster memoization

components/UI/FilterTimeMenu/FilterTimeMenu.tsx
**discord kullanıcı adı: @Caner Dagli#1251**
**closes #594**
* Donanım:
* Toolchain:
* SDK:
=> feat(#594): add new time options

components/UI/Map/ClusterGroup.tsx, components/UI/Map/LeafletMap.tsx, hooks/useMapClickHandlers.ts, package.json, yarn.lock
markers pluginini superclusters ile replace ediyor.
**discord kullanıcı adı: `umut#3072`**
**fixes #636 **
- Zoom in / zoom out yap
- clusterlara tikla
- prod ile ayni sekilde ama cooooook hizli calismasi lazim
=> refactor: use supercluster for leaflet clustering

components/UI/Map/ClusterGroup.tsx, hooks/useMapClickHandlers.ts
**discord kullanıcı adı: @afetharita#0001**
* Donanım:
* Toolchain:
* SDK:
=> fix: use correct cluster count

components/UI/FilterTimeMenu/FilterTimeMenu.tsx, components/UI/ReasoningFilterMenu/index.tsx, pages/index.tsx, styles/Home.module.css
**discord kullanıcı adı: autoMagic#2912**
**closes #641**
Siteye girin ve sağ üstte yeni dropdown eklendiğini görün.
=> feat: add filtering based on reason and channel

pages/index.tsx
gokata
* Donanım:
* Toolchain:
* SDK:
=> feat: hide sitesicon on mobile

components/UI/Map/ClusterGroup.tsx, components/UI/Map/LeafletMap.tsx, components/UI/Map/utils.ts, components/base/HeadWithMeta/HeadWithMeta.tsx
Kullanicinin son konumu ve zoom seviyesini localstorage'da tutulup sonraki ziyaretinde ayni konum ve zoom seviyesinde haritayi kullanabilmesi saglandi.
**discord kullanıcı adı: @Ercüment Laçın#2723**
**closes #556**
Masaüstü uzerinden testini sagladim.
* Donanım:
* Toolchain:
* SDK:
=> feat (#556): keep user's last info localstorage

pages/_document.tsx, pages/index.tsx
https://github.com/acikkaynak/deprem-yardim-frontend/issues/592 issue'sunda translate özelliği crash sebebiyle tamamen kaldırılmıştı. Fakat problemin kaynağı React ile ilgili, detaylı bilgi için bi yazı bırakıyorum;
https://guoyunhe.me/en/2019/06/02/fix-react-issues-with-google-translate/
"ALANI TARA" butonunun texti span'e sarıldı, böylece yukarıdaki yazıda bahsedilen problem çözülmüş oluyor.
Fakat ilerde bu sorunla karşılaşmamak için bu tarz conditional textlerin span'e sarılması önem arz ediyor.
**discord kullanıcı adı: İlker Sarıca#7138**
#601 
Lütfen yaptığınız …
=> fix(#601): google translate crash fix

pages/index.tsx
**discord kullanıcı adı: @namcojoulder#1062**
Reason filtresini daha once backend deploy bekledigimiz icin disable etmistik. Bu PR filtreyi geri acar.
* Firmware versiyonu: Firefox 102 ESR 
* Donanım: Debian 11
* Toolchain:
* SDK:
=> fix: reason filtersinin etkinlestirilmesi

pages/index.tsx
reason filtresi diger filtrelerle birlikte calisacak sekilde duzeltildi
**discord kullanıcı adı: @namcojoulder#1062**
**closes #673 **
* Donanım:
* Toolchain:
* SDK:
=> fix(#673): reason filtresi cozuldu

pages/index.tsx
**discord kullanıcı adı: @Jickless#8083**
**closes #639**
useSWR coordinates undefined olsa bile istek atıyor çünkü url undefined değil. Bu yüzden `coordinatesAndEventType` check edip, eğer undefined'sa paused yapabiliriz.
Local ortamda network incelenerek test edildi.
* Donanım: Macbook air m1
* Toolchain:
* SDK:
=> fix(#639): unnecessary requests on load with undefined

components/UI/Map/LayerControl.tsx
Pin noktaları layer üzerinde gruplamarak duplicate problemi çözüldü.
**discord kullanıcı adı: @Cytris#1329**
**closes #656 **
Local ortamda ekranda gösterilen değerler incelendi ve doğruluğu teyit edildi.
* Donanım: Macbook Pro M1
* Toolchain:
* SDK:
=> fix(#656): Duplicated clusters grouped

.github/ISSUE_TEMPLATE/bug_report.md
Translated bug_report.md to english
**discord kullanıcı adı: @Rayberk#8996**
* Donanım:
* Toolchain:
* SDK:
=> Translated bug_report.md to english

.github/ISSUE_TEMPLATE/feature_request.md
Same as in title.
**discord kullanıcı adı: @nejatcanunlu | Coniun#5462**
* Donanım:
* Toolchain:
* SDK:
=> Translated the feature request issue template to English.

components/UI/Drawer/components/MapButtons.tsx
Bazi cihazlarda alinan hatalar yuzunden google marker koyma linki degistirildi. 
**discord kullanıcı adı: cemiluzunhasan#5776**
**closes #541 **
Degisiklikler:
1. "Google Haritalarda Ac" buttonunun yonlendirdigi link degistirildi
Yapilan testler macOS ve iOS cihazlarda test edildi. 
* Donanım: Macbook Pro 13
* Toolchain:
* SDK:
=> fix(#541): harita - google maps link degisimi

.github/ISSUE_TEMPLATE/refactor-request.md
**discord kullanıcı adı: nejatcanunlu | Coniun#5462**
* Donanım:
* Toolchain:
* SDK:
=> Translated `refactor-request.md`.

.github/PULL_REQUEST_TEMPLATE.md
**discord kullanıcı adı: @afetharita#0001**
* Donanım:
* Toolchain:
* SDK:
=> Translated PULL_REQUEST_TEMPLATE.md to english

components/UI/Drawer/components/channels/babala/FeedChannelBabala.tsx, components/UI/Drawer/components/types.ts, mocks/TypesAreasEndpoint.ts, utils/dataTransformer.ts
#Description
UI improvements on babala content 
**discord: @ezranbayantemur**
**closes #686**
=> refactor(#686): babala feed content improvements

CODEOWNERS
**discord username: afetharita#0001**
Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.
## Things to check before creating a PR
Please describe the tests you did to test the changes you made. Please also specify your test configuration.
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
=> feat: add codeowners
